export default theme => ({
  richText: {
    paddingTop: theme.spacing(5),
    marginBottom: theme.spacing(4),
    position: 'relative',
    '&:before': {
      content: '""',
      position: 'absolute',
      background: theme.palette.tertiary.main,
      height: 20,
      right: 0,
      top: 0,
      width: '100vw',
      zIndex: -1,
    },
    '& h2': {
      fontSize: '1.875rem',
      fontWeight: 700,
      marginTop: theme.spacing(6.25),
      marginBottom: theme.spacing(2.5),
      marginLeft: 0,
      marginRight: theme.spacing(2.5),
      position: 'relative',
      background: theme.palette.common.white,
      padding: theme.spacing(2),
      paddingBottom: 0,
      [theme.breakpoints.up('md')]: {
        fontSize: '2.25rem',
      },

      '&:before': {
        content: '""',
        position: 'absolute',
        background: theme.palette.common.black,
        right: -20,
        top: -20,
        width: '100vw',
        zIndex: -1,
        backgroundColor: theme.palette.tertiary.main,
        height: 'calc(100% - .15em)',
      },
    },
    '& h3': {
      fontSize: '1.5rem',
      fontWeight: 400,
      margin: 0,
      marginBottom: theme.spacing(1),
      [theme.breakpoints.up('md')]: {
        fontSize: '1.875rem',
      },
    },
    '& p': {
      fontSize: '.875rem',
      margin: 0,
      marginBottom: theme.spacing(2),
      [theme.breakpoints.up('md')]: {
        fontSize: '1.125rem',
      },
    },
    '& div': {
      margin: 0,
      marginBottom: theme.spacing(2),
    },
    '& a': {
      color: theme.palette.common.black,
      position: 'relative',
      textDecoration: 'none',
      display: 'inline-block',
      '&:before': {
        content: '""',
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        height: 2,
        backgroundColor: theme.palette.primary.main,
        transition: 'all 0.3s ease-in-out',
      },
      '&:after': {
        content: '""',
        position: 'absolute',
        left: 0,
        right: '100%',
        bottom: 0,
        height: 2,
        backgroundColor: theme.palette.common.black,
        transition: 'all 0.3s ease-in-out',
      },
      '&:hover:after': {
        right: 0,
      },
    },
    '& figure': {
      margin: 0,
      marginBottom: theme.spacing(2),
    },
    '& .c-product': {
      marginBottom: theme.spacing(3.75),
      marginTop: theme.spacing(3.75),
      textAlign: 'center',
      position: 'relative',
    },
    '& .c-product__name': {
      fontSize: '.875rem',
      fontWeight: 700,
      maxWidth: '80%',
      margin: 'auto',
      paddingBottom: theme.spacing(0.375),
      '& span': {
        backgroundImage: `linear-gradient(120deg,${theme.palette.secondary.main} 0%,${theme.palette.secondary.main} 100%)`,
        backgroundRepeat: 'no-repeat',
        backgroundSize: '100% .1875rem',
        backgroundPosition: '0 100%',
      },
      [theme.breakpoints.up('md')]: {
        fontSize: '1.125rem',
      },
    },
    '& .c-product__tagline': {
      marginBottom: theme.spacing(1.25),
      '& span': {
        fontSize: '1.125rem',
        fontWeight: 700,
        background: `linear-gradient(to bottom,${theme.palette.common.white} 40%,${theme.palette.quaternary.main} 5%,${theme.palette.quaternary.main} 95%)`,
        display: 'inline-block',
      },
    },
    '& .c-product__image': {
      width: 250,
      margin: 'auto',
      position: 'relative',
    },
    '& .c-product__link': {
      '&:before, &:after': {
        display: 'none',
      },
    },
    '& .c-product__buy': {
      backgroundColor: theme.palette.primary.main,
      color: theme.palette.common.white,
      paddingTop: theme.spacing(1),
      paddingBottom: theme.spacing(1),
      paddingRight: theme.spacing(1.5),
      paddingLeft: theme.spacing(1.5),
      fontSize: '.875rem',
      fontWeight: 700,
      position: 'absolute',
      bottom: 10,
      right: -30,
      transform: 'perspective(1px) translateZ(0)',
      '&:after': {
        display: 'none',
      },
      '&:before': {
        content: '""',
        position: 'absolute',
        zIndex: -1,
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        height: 'auto',
        background: theme.palette.common.black,
        transform: 'scaleX(0)',
        transformOrigin: '0 50%',
        transitionProperty: 'transform',
        transitionDuration: '0.3s',
        transitionTimingFunction: 'ease-out',
      },
      '&:hover:before': {
        transform: 'scaleX(1)',
      },
    },
  },
});
